// auth
export const FETCH_AUTH_DATA = 'FETCH_AUTH_DATA';
export const FETCH_AUTH_DATA_INVALID = 'FETCH_AUTH_DATA_INVALID';
export const FETCH_AUTH_DATA_COMPLETED = 'FETCH_AUTH_DATA_COMPLETED';
export const FETCH_AUTH_DATA_FAILED = 'FETCH_AUTH_DATA_FAILED';

// auth user's todos
export const FETCH_AUTH_TODO_DATA = 'FETCH_AUTH_TODO';
export const FETCH_AUTH_TODO_COMPLETED = 'FETCH_AUTH_TODO_COMPLETED';
export const FETCH_AUTH_TODO_FAILED = 'FETCH_AUTH_TODO_FAILED';

// export const FETCH_AUTH_TODO_DATA = 'FETCH_AUTH_TODO';
// export const FETCH_AUTH_TODO_COMPLETED = 'FETCH_AUTH_TODO_COMPLETED';
// export const FETCH_AUTH_TODO_FAILED = 'FETCH_AUTH_TODO_FAILED';